### ISSUE TITLE
Holding Shift Does Not Produce Desired Effect on Windows

### ISSUE THREAD

**Issue by Jutanium** [akivajgordon/tikkun.io#54] opened 2020-02-20 23:00 UTC
On my mac browsers, holding shift changes the view while shift is held; on windows, though, it oscillates back and forth while you hold shift.

**Comment by akivajgordon** [comment] 2020-02-21 02:07
That is definitely not intended behavior – thanks for reporting! I will try to get a hold of a Windows machine to reproduce this and see if I can fix it. In the meantime, could you tell me which Windows OS and which browser you were using?

**Comment by akivajgordon** [comment] 2020-02-25 04:05
@Jutanium I tried this briefly on a Windows 10 machine but was not able to reproduce this in Chrome nor Firefox. The app didn't load correctly on IE or Edge (which is a separate issue), so I couldn't try it there.

I'm going to close this until I can get details on how to reproduce the issue, after which I'd be happy to reopen.

**Closed as completed by akivajgordon** 2020-02-25 04:05 UTC

**Comment by Jutanium** [comment] 2020-02-25 05:14
I'm on Chrome 80 on Windows 10, but the issue also happens for me on Firefox (version 73.0.1).

**Comment by akivajgordon** [comment] 2020-02-25 18:27
Hmm, I tried on Chrome 78 and Firefox 70 (the machine isn't mine so I can't download newer versions) but still was not able to reproduce this. I wonder if maybe you have some desktop setting that is causing the Shift key to automatically toggle.

Is there a way to confirm that another app or page that utilizes the Shift key is not behaving in the same way?

**Comment by Jutanium** [comment] 2020-02-25 19:42
Can you link me to the file where you register key events? I'll build it and fix it myself

**Comment by akivajgordon** [comment] 2020-02-26 02:28
Sure thing – I'd start over here: https://github.com/akivajgordon/tikkun.io/blob/07809e01ef531fb0c699a90128717bba82fb8615/index.js#L258

**Comment by Jutanium** [comment] 2020-02-27 00:31
I've fixed the issue and submitted a pull request. #56
