### ISSUE TITLE
Yitro Ta'am Elyon

### ISSUE THREAD

**Issue by BinyaminFarnoosh** [akivajgordon/tikkun.io#111] opened 2023-02-07 19:31 UTC
Is there a way to to get Ta'am elyon on the 10 Dibrot in Yitro.
Seems to be some regular and elyon mixed

**Comment by akivajgordon** [comment] 2023-02-07 21:40
@BinyaminFarnoosh Thanks for raising this! This is a duplicate of #63 , but thanks for reminding me. I probably won't have time this week, but hopefully I can resolve it before ואתחנן rolls around. So sorry about that.

**Closed as not planned by akivajgordon** 2023-02-07 21:40 UTC

**Comment by BinyaminFarnoosh** [comment] 2023-02-08 00:26
Thanks for explaining.
Kol tuv
